Add fixes based on feedback
eva-gallery/gallery pull request #17
Opened 2024-09-02 20:56 UTC by dudo50

@mdevecka

2024-09-07 16:11 UTC, dudo50 commented
@Teebor-Choka , @mdevecka , happy to notify you, that this is ready for review now! All functions tested/repaired to work with DB & IPFS where needed.

2024-09-09 13:18 UTC, mdevecka requested changes
We will need to add authentification to all backend nft routes.
To do that decorate all of your controllers with @UseGuards(AuthGuard).
Use @UserId() userId: string as a parameter in all endpoints. (see AdminController for reference).
Remove /:userID/ from route params and form body requests.
Use userId to validate whether current resource is available to that user.
If resource does not belong to that user or does not exist return appropriate status code.
If route should be accessed without authentification decorate with @Public() decorator.

2024-09-09 13:18 UTC, mdevecka commented on nft-module/src/modules/nftMinter/nft.service.ts
> +      if (metad) {
according to the deconstruction it does not seem to be possible that metad is not defined at this point

2024-09-10 09:14 UTC, mdevecka commented on backend/src/modules/nft-module/query_metadata/meta.controller.ts
>          error: error.message,
This could leak unwanted information to the user, use Logger instead.

2024-09-10 09:49 UTC, dudo50 commented
@mdevecka, please check your email. Pinging you in regards to Auth enhancement.

2024-09-10 12:41 UTC, dudo50 commented
@mdevecka nvm about the email, PR now again ready for recheck. Thanks for the input so far!

2024-09-11 08:41 UTC, dudo50 commented
@Teebor-Choka some feedback from you would also be appreciated. Thanks!

2024-09-11 11:02 UTC, mdevecka requested changes

2024-09-11 11:20 UTC, dudo50 commented on backend/src/modules/nft-module/create_collection/collection.controller.ts
> +  async updateDB(
@mdevecka , this will be handled in the front end. They cannot do this query without first processing the transaction. They also wouldn't be incentivized to do this because it will harm them as they do not own that specific collection meaning they cannot add any NFTs to it. So it wouldn't make sense to do this.

2024-09-11 11:22 UTC, dudo50 commented
@mdevecka I have added validation as requested. The only difference is, that it doesn't return bad request but null if the id doesn't match user

2024-09-11 13:05 UTC, mdevecka requested changes

2024-09-11 13:05 UTC, mdevecka commented on backend/src/modules/nft-module/query_metadata/meta.controller.ts
> -        return res.status(HttpStatus.INTERNAL_SERVER_ERROR).json({
this return statement is correct, restore to this

2024-09-11 13:05 UTC, mdevecka commented on backend/src/modules/nft-module/query_metadata/meta.controller.ts
> -      return res.status(HttpStatus.INTERNAL_SERVER_ERROR).json({
this return statement is correct, restore to this (just don't return error to user)

2024-09-11 13:05 UTC, mdevecka commented on backend/src/modules/nft-module/change_ownership/swap.controller.ts
> +    await this.appService.swapNFTOwnershipInDB(accountAddress, userId);
Throw BadRequest if this returns null.

2024-09-11 16:58 UTC, dudo50 commented on backend/src/modules/nft-module/change_ownership/swap.controller.ts
> +    await this.appService.swapNFTOwnershipInDB(accountAddress, userId);
@mdevecka This method doesn't return anything, should I rework it to return OK and BadRequestException?

2024-09-11 18:00 UTC, mdevecka commented on backend/src/modules/nft-module/change_ownership/swap.controller.ts
> +    await this.appService.swapNFTOwnershipInDB(accountAddress, userId);
You don't have to return OK, it is returned by default.

To clarify how this works in NestJS, by default if an exception is thrown and is not caught by application then NestJS will catch this exception, log it to default output and return status 500 (internal error) with default message.
However if you throw a special exception like NotFoundException or BadRequestException (all exception derived from HttpException), then this exception will be processed into status code instead and information will be returned to the user.
If there is no exception a default success status code (like 200/201) will be returned.
However if your endpoint method injects @Response() then this behavior is slightly changed which may cause confusion.
If you inject @Response() and don't set @Response({ passthrough: true }), then your endpoint method is expected to manually set status code and send response, and if you don't your methods will just stuck until timeout...
Imo it might have been better if NestJS used passthrough = true as default, but maybe the vast majority of default use cases just expect different.

2024-09-12 08:34 UTC, dudo50 commented on backend/src/modules/nft-module/change_ownership/swap.controller.ts
> +    await this.appService.swapNFTOwnershipInDB(accountAddress, userId);
Thanks, @mdevecka. I went ahead and modified other endpoints also. Also removed Res from metadata fetch and replaced it with exceptions built into nestJS.

PR is now ready for another recheck.

2024-09-12 10:02 UTC, mdevecka approved these changes

2024-09-12 10:18 UTC, dudo50 commented
cc @Teebor-Choka

2024-09-13 21:31 UTC, Teebor-Choka approved these changes

2024-09-14 06:47 UTC, merged