Add refactor
eva-gallery/gallery pull request #21
Opened 2024-09-16 20:52 UTC by dudo50

After consultation with LL Studio, I reworked certain endpoints & also added update endpoints allowing for metadata updates if user decides to update NFT metadata after NFT has been created

2024-09-19 09:28 UTC, dudo50 commented on backend/src/modules/nft-module/create_nft/nft.service.ts
> +    const user = await this.nftRepository.getUser(userId);
That is removed line a removed line 👍 But thanks!

2024-09-19 09:31 UTC, dudo50 commented on backend/src/modules/nft-module/create_nft/nft.service.ts
> +    const user = await this.nftRepository.getUser(userId);
Ah you meant different thing, gotcha, fixed now.

2024-09-19 09:43 UTC, dudo50 commented on backend/src/modules/nft-module/mint_trial/mint.service.ts
> +    if (!user && !artwork && user.trialMintClaimed == true && user.trialMint != null && user.trialMint != 'null') {
It shouldn't, I just added it for preventive matter.

Removed now.

2024-09-19 09:43 UTC, dudo50 commented on backend/src/modules/nft-module/create_nft/nft.controller.ts
> +    if (callData == null || callData == 'null') {
It shouldn't; I just added it as a preventive matter.

Removed now

2024-09-19 09:46 UTC, dudo50 commented on backend/src/modules/nft-module/mint_trial/mint.service.ts
> +    const artwork = await this.nftRepository.getArtwork(artworkId);
Taken care of by modifying getArtwork (Added userId to check)

2024-09-19 09:49 UTC, dudo50 commented on nft-module/src/modules/nftUpdater/dto/UpdaterDto.ts
> +  @Matches(/^[a-zA-Z0-9 ]*$/, {
It indeed has - IsString.

Replaced in all DTOs

2024-09-19 11:18 UTC, dudo50 commented
@mdevecka , I incorporated your suggested fixes. I also noticed that there is different convention when creating NFTs and updated both BE and NFT module to incorporate this as well. Metadata is not passed in string form rather all metadata is uploaded to IPFS (Along with image uploaded to IPFS as well). So onchain there is only one path to complete information about IPFS. Now all good and ready for recheck.

Thanks for feedback so far!

2024-09-23 16:13 UTC, dudo50 commented
@mdevecka , @Teebor-Choka - Added collection data querying and added collections to the entity. Users can now see which collections belong to them and will be able to create new NFTs in front end. Also NFTs are not strongly tied with collections because there may be some artworks that users own but collection is owned by someone else (They are unable to mint into that collection, but NFT can still be shown within FE). 

I believe PR is again ready for re-check

2024-09-27 15:22 UTC, mdevecka requested changes
By the separation of concerns principle it would be good if all nft related logic would be in one place.
Please move all ipfs create and api.tx calls to nft project + implement endpoints for fetching instead:
Move collection.service createCollectionCall to nft project.
Move nft.service.ts createNFTCall to nft project.
Move mint.service.ts createMint nft logic to nft project.
Backend dependence on @polkadot/api, ipfs-core and ipfs-http-client should be then removed.

2024-09-28 08:05 UTC, dudo50 commented on backend/src/modules/app-db/repositories/nft.repository.ts
> +    if (artwork && artwork.artist.user.id == userId) {
Resolved by adding entity loading via query as suggested.

2024-09-28 08:14 UTC, dudo50 commented
@mdevecka I have added all your required changes. I am now going to work on migrating NFT functionality to NFT module outside of BE. Will ping you again for recheck.

2024-09-28 17:21 UTC, dudo50 commented
@mdevecka ready for recheck. Also had to modify logic of change ownership, so user pays before collection is transferred to them (Unable to do them at the same time because for assigning new NFT owner Eva gallery wallet is used and for paying fees User address is used). So I added new boolean to User so we can easily check if they paid for the transfer of ownership.

2024-09-28 20:43 UTC, dudo50 commented
@mdevecka done testing of the endpoints on both NFT and Backend modules. I am unable to verify IPFS as of right now since for some reason IPFS server is down. I have notified person responsible for IPFS server. However nothing has changed from working configuration so should be just fine.

2024-09-29 15:17 UTC, mdevecka reviewed
Looking good, just some small fixes remaining.

2024-09-29 17:02 UTC, dudo50 commented
@mdevecka , added your required changes. As for exporting the function that signs transactions, I had to create service for it since using config service required class. I did not want to pass private key to a function. To avoid that I chose this route.

2024-09-30 07:22 UTC, mdevecka approved these changes

2024-09-30 07:22 UTC, mdevecka commented on nft-module/src/common/utils.ts
> +  ): Promise<string> {
I would like if you give some final thoughts to if the number of input parameters to this method could be reduced.
Considerations to be made:
- parameters that could be initialized within the scope of this function / service
- parameters that are not used within sign calls / computation of this function

2024-09-30 11:07 UTC, dudo50 commented on nft-module/src/common/utils.ts
> +  ): Promise<string> {
I did this to ensure that these parameters only return if the transaction was successful. I can rework it, however, so that none of these parameters are needed. I will have to handle errors then. Will push update soon

2024-09-30 11:19 UTC, dudo50 commented
@mdevecka  I have refactored sign function according to your requirement to be more generalized. 

Feel free to review again. Afterwards if no issue is found, I believe, we can merge! 🥳

2024-09-30 12:19 UTC, mdevecka approved these changes
Well done, let's merge.

2024-09-30 12:49 UTC, merged